spring.application.name=decathlon-scoring
spring.datasource.url=jdbc:postgresql://localhost:5432/decathlon
spring.datasource.username=decathlon
spring.datasource.password=decathlon
spring.jpa.hibernate.ddl-auto=update